name: flutter_figma
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  # UI / state
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.9
  image: ^4.1.3
  image_picker: ^1.2.0
  # Add path for extension parsing
  path: ^1.9.0
  path_provider: ^2.0.15
  rive: ^0.13.10
  flare_flutter: ^3.0.2
  confetti: ^0.7.0
  lottie: ^2.7.0
  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.7.0
  cloud_firestore: 5.6.12
  share_plus: ^10.0.2
  file_picker: ^8.1.2
  http: ^1.2.0
  permission_handler: ^11.0.0
  firebase_storage: ^12.4.10
  syncfusion_flutter_pdf: ^26.2.14
  google_mlkit_text_recognition: ^0.11.0
  # Offline storage / connectivity
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Hive code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  # Build-time tools (don't need to be in main dependencies)
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/generated-image.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/generated-image.png"
  web:
    generate: true
    image_path: "assets/images/generated-image.png"
  windows:
    generate: true
    image_path: "assets/images/generated-image.png"
  macos:
    generate: true
    image_path: "assets/images/generated-image.png"
  remove_alpha_ios: true
  adaptive_icon_mask: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/styles/